name: Triggering a build manually 

# A simple configuration file that allows you to trigger a build manually. 

on: 
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'     
        required: false

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Comment: ${{ github.event.inputs.comment }}"
  
  steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn assembly:assembly --file pom.xml

